#!/usr/bin/env python
import errno
import logging

from cocaine.exceptions import Error as CocaineError
from cocaine.tools import printer
from cocaine.tools.cli import ToolsError
from cocaine.tools.dispatcher import d


printer.ENABLE_OUTPUT = True


__author__ = 'EvgenySafronov <division494@gmail.com>'


__doc__ = '''Provides helpful tools for management, viewing, uploading and other actions with cocaine applications
and services'''


log = logging.getLogger('cocaine.tools')
# import sys
# log = 'cocaine.tools'
# logs = [log, 'cocaine.concurrent.deferred', 'cocaine.services.base']
# handler = logging.StreamHandler(stream=sys.stdout)
# for log in map(logging.getLogger, logs):
#     log.addHandler(handler)
#     log.setLevel(logging.DEBUG)
#     log.propagate = False


if __name__ == '__main__':
    try:
        d.dispatch()
    except (CocaineError, ToolsError) as err:
        log.error(err)
        exit(128)
    except ValueError as err:
        log.error(err)
        exit(errno.EINVAL)
    except KeyboardInterrupt:
        log.error('Terminated by user')
        exit(errno.ECANCELED)
    except Exception as err:
        log.error('Unknown error occurred - %s', err)
        exit(128)
